# Generated by Django 4.0.3 on 2022-06-23 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the company', max_length=100)),
                ('street', models.CharField(help_text='company street name and number', max_length=300)),
                ('L_G_A', models.CharField(help_text='local govername of location', max_length=70)),
                ('state', models.CharField(help_text='Company state', max_length=90)),
                ('country', models.CharField(default='NIGERIA', help_text='country of location', max_length=50)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('contact', models.IntegerField()),
                ('twitter_handel', models.CharField(help_text='company twitter profile', max_length=300, unique=True)),
                ('facebook', models.CharField(help_text='Facebook account', max_length=300)),
                ('instagram', models.CharField(help_text='instagram handel', max_length=700)),
                ('skype', models.CharField(help_text='skype handel', max_length=700)),
                ('linkin', models.CharField(help_text='linkage handel', max_length=700)),
                ('logo', models.ImageField(upload_to='staics/img/companyLogo')),
            ],
        ),
    ]
