# Generated by Django 4.0.3 on 2022-07-09 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyid',
            name='logo',
            field=models.ImageField(upload_to='companyLogo'),
        ),
    ]
