# Generated by Django 4.0.3 on 2022-07-09 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bangles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media?Bangle')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('descriptions', models.TextField()),
                ('type', models.CharField(default='long', max_length=150)),
                ('fprice', models.IntegerField(help_text='first price')),
                ('lprice', models.IntegerField(help_text='Last price')),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Belt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/belt')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('descriptions', models.TextField()),
                ('fprice', models.IntegerField(help_text='first price')),
                ('lprice', models.IntegerField(help_text='Last price')),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/caps')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('size', models.IntegerField(default=30)),
                ('descriptions', models.TextField()),
                ('fprice', models.IntegerField(help_text='first price')),
                ('lprice', models.IntegerField(help_text='Last price')),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/chains')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(default='Gold', max_length=200)),
                ('descriptions', models.TextField()),
                ('fprice', models.IntegerField(help_text='first price')),
                ('lprice', models.IntegerField(help_text='Last price')),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='cloths_Adult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/adult/cloths')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('size', models.IntegerField(default=36)),
                ('descriptions', models.TextField()),
                ('color', models.CharField(max_length=120)),
                ('fprice', models.IntegerField(help_text='first price')),
                ('lprice', models.IntegerField(help_text='Last price')),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cloths_Children',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/children/cloths')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('size', models.IntegerField(default=36)),
                ('descriptions', models.TextField()),
                ('fprice', models.IntegerField(help_text='first price')),
                ('lprice', models.IntegerField(help_text='Last price')),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Engagement_Rings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/engangement_Rings')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('size', models.IntegerField(default=36)),
                ('descriptions', models.TextField()),
                ('fprice', models.IntegerField(help_text='first price')),
                ('lprice', models.IntegerField(help_text='Last price')),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Glasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/glasses')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('fprice', models.IntegerField(help_text='first price')),
                ('descriptions', models.TextField()),
                ('color', models.CharField(default='black', max_length=100)),
                ('lprice', models.IntegerField(help_text='Last price')),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marriage_Rings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/marriage_ring')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('size', models.IntegerField(default=36)),
                ('descriptions', models.TextField()),
                ('fprice', models.IntegerField(help_text='first price')),
                ('lprice', models.IntegerField(help_text='Last price')),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Neckless',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/neckless')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('descriptions', models.TextField()),
                ('fprice', models.IntegerField(help_text='first price')),
                ('lprice', models.IntegerField(help_text='Last price')),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Other_Rings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/other_rings')),
                ('name', models.CharField(max_length=1000, unique=True)),
                ('size', models.IntegerField(default=36)),
                ('descriptions', models.TextField()),
                ('fprice', models.IntegerField(help_text='first price')),
                ('lprice', models.IntegerField(help_text='Last price')),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shoes_Adult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/adult/shoes')),
                ('size', models.IntegerField(default=34)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('descriptions', models.TextField()),
                ('fprice', models.IntegerField(help_text='first price')),
                ('lprice', models.IntegerField(help_text='Last price')),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shoes_children',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/children/shoes')),
                ('size', models.IntegerField(default=20)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('fprice', models.IntegerField(help_text='first price')),
                ('lprice', models.IntegerField(help_text='Last price')),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wrist_watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/watches')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('descriptions', models.TextField()),
                ('fprice', models.IntegerField(help_text='first price')),
                ('lprice', models.IntegerField(help_text='Last price')),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
