# Generated by Django 4.0.3 on 2022-07-09 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bangles',
            name='image',
            field=models.ImageField(upload_to='Bangle'),
        ),
        migrations.AlterField(
            model_name='belt',
            name='image',
            field=models.ImageField(upload_to='belt'),
        ),
        migrations.AlterField(
            model_name='chains',
            name='image',
            field=models.ImageField(upload_to='chains'),
        ),
        migrations.AlterField(
            model_name='cloths_adult',
            name='image',
            field=models.ImageField(upload_to='adult/cloths'),
        ),
        migrations.AlterField(
            model_name='cloths_children',
            name='image',
            field=models.ImageField(upload_to='children/cloths'),
        ),
        migrations.AlterField(
            model_name='engagement_rings',
            name='image',
            field=models.ImageField(upload_to='engangement_Rings'),
        ),
        migrations.AlterField(
            model_name='marriage_rings',
            name='image',
            field=models.ImageField(upload_to='marriage_ring'),
        ),
        migrations.AlterField(
            model_name='neckless',
            name='image',
            field=models.ImageField(upload_to='neckless'),
        ),
        migrations.AlterField(
            model_name='other_rings',
            name='image',
            field=models.ImageField(upload_to='other_rings'),
        ),
        migrations.AlterField(
            model_name='shoes_adult',
            name='image',
            field=models.ImageField(upload_to='adult/shoes'),
        ),
        migrations.AlterField(
            model_name='shoes_children',
            name='image',
            field=models.ImageField(upload_to='children/shoes'),
        ),
        migrations.AlterField(
            model_name='wrist_watch',
            name='image',
            field=models.ImageField(upload_to='watches'),
        ),
    ]
