# Generated by Django 4.0.3 on 2022-07-20 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_alter_bangles_image_alter_belt_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(help_text='Enter the categoty of the product', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='enter the product name', max_length=50)),
                ('desc', models.CharField(help_text='Enter the product', max_length=250)),
                ('price', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='media/<django.db.models.fields.related.ForeignKey>/')),
                ('fprice', models.IntegerField(help_text='first price')),
                ('lprice', models.IntegerField(help_text='Last price')),
                ('is_available', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.category')),
            ],
        ),
        migrations.DeleteModel(
            name='Bangles',
        ),
        migrations.DeleteModel(
            name='Belt',
        ),
        migrations.DeleteModel(
            name='Cap',
        ),
        migrations.DeleteModel(
            name='Chains',
        ),
        migrations.DeleteModel(
            name='cloths_Adult',
        ),
        migrations.DeleteModel(
            name='Cloths_Children',
        ),
        migrations.DeleteModel(
            name='Engagement_Rings',
        ),
        migrations.DeleteModel(
            name='Glasses',
        ),
        migrations.DeleteModel(
            name='Marriage_Rings',
        ),
        migrations.DeleteModel(
            name='Neckless',
        ),
        migrations.DeleteModel(
            name='Other_Rings',
        ),
        migrations.DeleteModel(
            name='Shoes_Adult',
        ),
        migrations.DeleteModel(
            name='Shoes_children',
        ),
        migrations.DeleteModel(
            name='Wrist_watch',
        ),
    ]
